"""
Statefully builds OBJ commands, including animations and materials.

Takes in OBJ directives and their parameters and outputs at the end Blender datablocks
"""
import collections
import copy
import itertools
import math
import pathlib
import random
import re
from dataclasses import dataclass, field
from itertools import islice, tee
from pathlib import Path
from pprint import pprint
from typing import (
    Any,
    Callable,
    Deque,
    Dict,
    Iterator,
    List,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
    Union,
)

import bmesh
import bpy
from mathutils import Euler, Matrix, Quaternion, Vector

from io_xplane2blender.tests import test_creation_helpers
from io_xplane2blender.tests.test_creation_helpers import (
    DatablockInfo,
)

# AxisAngle was removed from test_creation_helpers in 4.3.x — define it locally.
from collections import namedtuple
AxisAngle = namedtuple("AxisAngle", ["axis", "angle"])


@dataclass
class ParentInfo:
    """
    Internal parent-info that stores the parent as a NAME string during parsing,
    before any Blender objects exist. The 4.3.x test_creation_helpers.ParentInfo
    requires a bpy.types.Object at construction time, so we use our own here and
    resolve to real Objects only in finalize_intermediate_blocks.
    """
    parent: Optional[str] = None   # Blender object name, or None
    parent_type: str = "OBJECT"
    parent_bone: Optional[str] = None
from io_xplane2blender.xplane_constants import (
    ANIM_TYPE_HIDE,
    ANIM_TYPE_SHOW,
    ANIM_TYPE_TRANSFORM,
    COCKPIT_FEATURE_DEVICE,
    COCKPIT_FEATURE_NONE,
    COCKPIT_FEATURE_PANEL,
    EXPORT_TYPE_COCKPIT,
    MANIP_AXIS_KNOB,
    MANIP_AXIS_SWITCH_LEFT_RIGHT,
    MANIP_AXIS_SWITCH_UP_DOWN,
    MANIP_COMMAND,
    MANIP_COMMAND_AXIS,
    MANIP_COMMAND_KNOB,
    MANIP_COMMAND_KNOB2,
    MANIP_COMMAND_SWITCH_LEFT_RIGHT,
    MANIP_COMMAND_SWITCH_LEFT_RIGHT2,
    MANIP_COMMAND_SWITCH_UP_DOWN,
    MANIP_COMMAND_SWITCH_UP_DOWN2,
    MANIP_DELTA,
    MANIP_DRAG_AXIS,
    MANIP_DRAG_AXIS_DETENT,
    MANIP_DRAG_AXIS_PIX,
    MANIP_DRAG_ROTATE,
    MANIP_DRAG_ROTATE_DETENT,
    MANIP_DRAG_XY,
    MANIP_NOOP,
    MANIP_PUSH,
    MANIP_RADIO,
    MANIP_TOGGLE,
    MANIP_WRAP,
    PANEL_COCKPIT,
    PANEL_COCKPIT_LIT_ONLY,
    PANEL_COCKPIT_REGION,
    PRECISION_KEYFRAME,
)
from io_xplane2blender.xplane_helpers import (
    ExportableRoot,
    floatToStr,
    logger,
    round_vec,
    vec_b_to_x,
    vec_x_to_b,
)

# is_vector_axis_aligned was removed from xplane_helpers in 4.3.x — define locally.
def is_vector_axis_aligned(v) -> bool:
    """Returns True if v is approximately aligned with the X, Y, or Z axis."""
    return sum(1 for c in v if round(abs(c), PRECISION_KEYFRAME) != 0) == 1


@dataclass
class IntermediateDataref:
    """
    Matches xplane_props.XPlaneDataref.

    Made since dataclasses are more flexible then bpy.types.PropertyGroups.
    """

    anim_type: str = ANIM_TYPE_TRANSFORM
    loop: float = 0.0
    path: str = ""
    show_hide_v1: float = 0
    show_hide_v2: float = 0
    location_values: List[float] = field(default_factory=list)
    rotation_values: List[float] = field(default_factory=list)

    def __hash__(self):
        return hash(
            (
                self.anim_type,
                self.loop,
                self.path,
                self.show_hide_v1,
                self.show_hide_v2,
                tuple(self.location_values),
                tuple(self.rotation_values),
            )
        )


@dataclass
class IntermediateAnimation:
    """
    An animation is everything generated by one pair of ANIM_trans/rotate pair (or
    the static version). An IntermediateDatablock may have 0 or more of these.
    """

    # Blender Locations, pair with location_values
    # in xp_dataref
    locations: List[Vector] = field(default_factory=list)

    # Axis of rotations and the degrees of rotation along them.
    # - Will be empty, have 1 Off Axis Axis Angle, or 1 to 3 Axis Aligned Axis (
    # interpreted as a Euler)
    # - Must be paired with rotation_mode to have meaning
    # - Pairs perfectly with rotation_values in xp_dataref
    rotations: Dict[Vector, List[float]] = field(
        default_factory=lambda: collections.defaultdict(list)
    )
    xp_dataref: IntermediateDataref = field(
        default_factory=lambda: IntermediateDataref()
    )

    def apply_animation(self, bl_object: bpy.types.Object):
        """
        Applies any collected animations to a Blender Object
        """

        def recompose_rotation(
            rotation_mode: str, keyframe_idx: int
        ) -> Union[AxisAngle, Euler]:
            """
            Extract rotation at rotation keyframe idx,
            for use in KeyframeInfo.

            Rotations must be either
            - 1 AxisAngle
            - 1 to 3 axis that are all axis aligned
            - 1 to n axis that are not all axis aligned
            """
            if rotation_mode == "AXIS_ANGLE":
                axis, rotations = next(iter(self.rotations.items()))
                # 4.3.x KeyframeInfo expects (angle, axis) tuple for AXIS_ANGLE
                return (math.radians(rotations[keyframe_idx]), Vector(axis))
            else:

                def axis_to_label(axis):
                    r_axis = tuple(
                        map(lambda c: abs(int(round(c, PRECISION_KEYFRAME))), axis)
                    )
                    return {
                        (1, 0, 0): "X",
                        (0, 1, 0): "Y",
                        (0, 0, 1): "Z",
                    }[r_axis]

                # With this we become immune to any mutations to self.rotations order, but instead rely that
                # rotation_mode is absolutely right
                rotations = {
                    axis_to_label(axis): (axis, degrees)
                    for axis, degrees in self.rotations.items()
                }
                euler_components = {"X": 0, "Y": 0, "Z": 0}
                for axis_label, (axis, degrees) in rotations.items():
                    r_axis = tuple(
                        map(lambda c: bool(round(c, PRECISION_KEYFRAME)), axis)
                    )

                    # Remember, all axis are normalized, so we're okay
                    euler_components[axis_label] = axis[
                        r_axis.index(True)
                    ] * degrees[keyframe_idx]

                tot_rot = Euler(euler_components.values(), rotation_mode)
                return tot_rot

        if self.xp_dataref.anim_type == ANIM_TYPE_TRANSFORM:
            keyframe_infos = []
            current_frame = 1
            for value_idx, value in enumerate(self.xp_dataref.location_values):
                keyframe_infos.append(
                    test_creation_helpers.KeyframeInfo(
                        idx=current_frame,
                        dataref_path=self.xp_dataref.path,
                        dataref_value=value,
                        dataref_anim_type=self.xp_dataref.anim_type,
                        location=self.locations[value_idx] + bl_object.location
                        if self.locations
                        else None,
                    )
                )
                current_frame += 1
            current_frame = 1
            for value_idx, value in enumerate(self.xp_dataref.rotation_values):
                keyframe_infos.append(
                    test_creation_helpers.KeyframeInfo(
                        idx=current_frame,
                        dataref_path=self.xp_dataref.path,
                        dataref_value=value,
                        dataref_anim_type=self.xp_dataref.anim_type,
                        location=None,
                        rotation=recompose_rotation(bl_object.rotation_mode, value_idx)
                        if self.rotations
                        else None,
                        rotation_mode=bl_object.rotation_mode,
                    )
                )
                current_frame += 1
        else:
            keyframe_infos = [
                test_creation_helpers.KeyframeInfo(
                    idx=1,
                    dataref_path=self.xp_dataref.path,
                    dataref_show_hide_v1=self.xp_dataref.show_hide_v1,
                    dataref_show_hide_v2=self.xp_dataref.show_hide_v2,
                    dataref_anim_type=self.xp_dataref.anim_type,
                )
            ]

        test_creation_helpers.set_animation_data(bl_object, keyframe_infos)
        current_frame = 1

    @property
    def is_animated_location(self) -> bool:
        return self.locations and self.xp_dataref.location_values

    @property
    def is_animated_rotation(self) -> bool:
        return self.rotations and self.xp_dataref.rotation_values

    """
    # Always
    # - You will have one of (type == "TRANSFORM" and (locations xor rotations) or (type == "SHOW"/"HIDE")
    # - locations cannot be "merged" for the same set of values, they are replaced instead, TODO: Is that true? "translations can dance around each other in each 'room'"
    # - All axis in rotations will be unit length
    # - locations and each axis's degrees list must equal the dataref's values list
    def is_valid_prior_optimization(self) -> bool:
        # - rotations will have a length of 0 or 1
        if self.xp_dataref.anim_type == ANIM_TYPE_TRANSFORM:
            exclusive_use = (self.locations and not self.rotations) or (
                not self.locations and self.rotations
            )
            # TODO: Support AngleAxis
            return exclusive_use and is_vector_axis_aligned(next(self.rotations
        else:
            return not self.locations and not self.rotations
    def is_valid_post_optimization(self)-> bool:
        # - rotations dict may have 0-3 entries, See doc for rotations according to rules of being AA or Euler
    """


@dataclass
class IntermediateManipulator:
    """Holds all data parsed from ATTR_manip_* and related directives."""

    manip_type: str
    cursor: str = ""
    tooltip: str = ""
    dx: float = 0.0
    dy: float = 0.0
    dz: float = 0.0
    v1: float = 0.0
    v2: float = 0.0
    v1_min: float = 0.0
    v1_max: float = 0.0
    v2_min: float = 0.0
    v2_max: float = 0.0
    v_down: float = 0.0
    v_up: float = 0.0
    v_hold: float = 0.0
    v_on: float = 0.0
    v_off: float = 0.0
    step: float = 1.0
    click_step: float = 0.0
    hold_step: float = 0.0
    exp: float = 1.0
    wheel_delta: float = 0.0
    command: str = ""
    positive_command: str = ""
    negative_command: str = ""
    dataref1: str = ""
    dataref2: str = ""
    # drag_rotate specific (X-Plane coordinate space, stored as custom props on import)
    origin: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    axis: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    angle1: float = 0.0
    angle2: float = 0.0
    lift_at_max: float = 0.0
    # ATTR_axis_detented specific
    has_axis_detented: bool = False
    detent_axis: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    detent_v1_min: float = 0.0
    detent_v1_max: float = 0.0
    detent_dataref: str = ""
    axis_detent_ranges: List[Tuple[float, float, float]] = field(default_factory=list)
    keyframes: List[Tuple[float, float]] = field(default_factory=list)


@dataclass
class IntermediateAttributes:
    """Persistent OBJ attribute state active when a TRIS block is parsed."""

    draw: bool = True
    cockpit_mode: str = COCKPIT_FEATURE_NONE
    cockpit_region: int = 0
    cockpit_device_args: Tuple[str, ...] = ()
    solid_camera: bool = False
    shiny_rat: Optional[float] = None
    has_explicit_shiny_rat: bool = False

    def material_key(self) -> Tuple[Any, ...]:
        return (
            self.draw,
            self.cockpit_mode,
            self.cockpit_region,
            self.cockpit_device_args,
            self.solid_camera,
            self.shiny_rat,
            self.has_explicit_shiny_rat,
        )


@dataclass
class IntermediateDatablock:

    # You'll want to change this as little as possible.
    # If a property replacement exists, use it!
    #
    # DO NOT attempt to use .location or .rotation
    datablock_info: DatablockInfo

    # If Datablock is a MESH, these will correspond to (hopefully valid) entries in the idx table and _VT table
    start_idx: Optional[int]
    count: Optional[int]
    transform_animation: Optional[IntermediateAnimation]
    show_hide_animations: List[IntermediateAnimation]

    bake_matrix: Matrix

    # Why here? DatablockInfos are meant to be isolated structs as much as possible
    # and we're interested in the relationship between IntermediateDatablocks
    # and their animations which isn't data a DatablockInfo has
    children: List["IntermediateDatablock"] = field(default_factory=list)
    manip: Optional["IntermediateManipulator"] = None
    attrs: Optional[IntermediateAttributes] = None

    def build_mesh(self, vt_table: "VTTable") -> bpy.types.Mesh:
        """
        Builds a mesh from the OBJ's VT Table, raises ValueError if
        an object with that mesh couldn't be built
        """
        mesh_idxes = vt_table.idxes[self.start_idx : self.start_idx + self.count]

        vertex_map_old_to_new = {}
        vertices = []
        for idx in mesh_idxes:
            if idx not in vertex_map_old_to_new:
                vertices.append(vt_table.vertices[idx])
                vertex_map_old_to_new[idx] = len(vertices) - 1
            else:
                pass
        idxes = [vertex_map_old_to_new[idx] for idx in mesh_idxes]
        normals = [(v.nx, v.ny, v.nz) for v in vertices]
        uvs = [Vector((v.s, v.t)) for v in vertices]

        # Thanks senderle, https://stackoverflow.com/a/22045226
        def chunk(it, size):
            it = iter(it)
            return iter(lambda: tuple(itertools.islice(it, size)), ())

        py_vertices = [(v.x, v.y, v.z) for v in vertices]
        py_faces: List[Tuple[int, int, int]] = [
            # We reverse the winding order to reverse the faces
            face[::-1]
            for face in chunk(idxes, 3)
        ]

        me = bpy.data.meshes.new(self.name)
        me.from_pydata(py_vertices, [], py_faces)

        if not me.validate(verbose=True):
            # Thanks Dave Prue and their "Import X-Plane Object" addon for the API example
            me.uv_layers.new()

            for mesh_uv_loop, mesh_loop in zip(me.uv_layers[-1].data, me.loops):
                mesh_uv_loop.uv = uvs[mesh_loop.vertex_index]

            # vertex.normal is read-only in Blender 4.x; normals are computed automatically
            me.update(calc_edges=True)
            # 4.3.x create_datablock_mesh no longer accepts a pre-built Mesh
            # object, so create the Blender object directly.
            if self.datablock_info.parent_info is not None and isinstance(
                self.datablock_info.parent_info.parent, str
            ):
                resolved = bpy.data.objects.get(self.datablock_info.parent_info.parent)
                if resolved is not None:
                    self.datablock_info.parent_info.parent = resolved
            ob = bpy.data.objects.new(self.name, object_data=me)
            test_creation_helpers.set_collection(ob, self.datablock_info.collection)
            ob.name = self.datablock_info.name if self.datablock_info.name is not None else ob.name
            if self.datablock_info.parent_info:
                test_creation_helpers.set_parent(ob, self.datablock_info.parent_info)
            if not ob.data.uv_layers:
                ob.data.uv_layers.new()

            return ob
        else:
            logger.error(
                f"Mesh was not valid, object '{self.name}' not made, check console for more"
            )
            raise ValueError

    @property
    def name(self) -> str:
        return self.datablock_info.name

    @property
    def parent(self) -> Optional[str]:
        try:
            return self.datablock_info.parent_info.parent
        except AttributeError:
            return None

    @parent.setter
    def parent(self, value: str) -> None:
        self.datablock_info.parent_info.parent = value

    @property
    def datablock_type(self) -> str:
        return self.datablock_info.datablock_type

    @property
    def is_animated(self) -> bool:
        return self.transform_animation or self.show_hide_animations

    @property
    def rotation_mode(self) -> str:
        """
        Calculates the final rotation_mode based on
        the back matrix and any animations it has.
        """
        # If its rotation or one of its animated rotations (if applicable)
        # is not axis_aligned, our Object will have Axis Angle rotation mode
        is_axis_aligned = is_vector_axis_aligned(
            self.bake_matrix.to_quaternion().to_axis_angle()[0]
        )
        if not self.transform_animation and is_axis_aligned:
            rotation_mode = "XYZ"
        elif not self.transform_animation and not is_axis_aligned:
            rotation_mode = "AXIS_ANGLE"
        # This is a very generalized check. See the rules for the rotations dict
        # in its definition
        elif any(
            not is_vector_axis_aligned(axis)
            for axis in self.transform_animation.rotations
        ):
            rotation_mode = "AXIS_ANGLE"
        else:
            # This is already figured out in finalize_intermediate_blocks
            rotation_mode = self.datablock_info.rotation_mode

        return rotation_mode


@dataclass
class VT:
    """Where xyz, nxyz are in Blender coords"""

    x: float
    y: float
    z: float
    nx: float
    ny: float
    nz: float
    s: float
    t: float

    def __post_init__(self):
        for attr, factory in type(self).__annotations__.items():
            try:
                setattr(self, attr, factory(getattr(self, attr)))
            except ValueError:
                print(
                    f"Couldn't convert '{attr}''s value ({getattr(self, attr)}) with {factory}"
                )

    def __str__(self) -> str:
        def fmt(s):
            try:
                return floatToStr(float(s))
            except (TypeError, ValueError):
                return s

        return "\t".join(
            fmt(value)
            for attr, value in vars(self).items()
            if not attr.startswith("__")
        )


@dataclass
class VTTable:
    vertices: List[VT] = field(default_factory=list)
    idxes: List[int] = field(default_factory=list)


@dataclass
class _AnimIntermediateStackEntry:
    animation: IntermediateAnimation
    intermediate_datablock: Optional[IntermediateDatablock]


class ImpCommandBuilder:
    def __init__(self, filepath: Path):
        self.root_collection = test_creation_helpers.create_datablock_collection(
            pathlib.Path(filepath).stem
        )

        self.root_collection.xplane.is_exportable_collection = True
        self.vt_table = VTTable([], [])
        self.texture: Optional[Path] = None
        self.texture_lit: Optional[Path] = None
        self.texture_normal: Optional[Path] = None
        self.is_cockpit: bool = False

        # Although we don't end up making this, it is useful for tree problems
        self.root_intermediate_datablock = IntermediateDatablock(
            datablock_info=DatablockInfo(
                datablock_type="EMPTY",
                name="INTER_ROOT",
                collection=self.root_collection,
            ),
            start_idx=None,
            count=None,
            transform_animation=None,
            show_hide_animations=[],
            bake_matrix=Matrix.Identity(4),
        )

        # --- Animation Builder States ----------------------------------------
        # Instead of build at separate parent/child relationship in Datablock info, we just save everything we make here
        self._blocks: List[IntermediateDatablock] = [self.root_intermediate_datablock]
        self._last_axis: Optional[Vector] = None
        self._anim_intermediate_stack: Deque[
            _AnimIntermediateStackEntry
        ] = collections.deque()
        self._anim_count: Sequence[int] = collections.deque()
        self._bake_matrix_stack: Deque[Matrix] = collections.deque((Matrix(),))
        self._pending_manip: Optional[IntermediateManipulator] = None
        self._pending_attrs: IntermediateAttributes = IntermediateAttributes()
        self._materials_by_attr_key: Dict[Tuple[Any, ...], bpy.types.Material] = {}
        self._cockpit_panel_mode: Optional[str] = None
        # ---------------------------------------------------------------------

    def build_cmd(
        self, directive: str, *args: List[Union[float, int, str]], name_hint: str = ""
    ):
        """
        Given the directive and it's arguments, correctly handle each case.

        args must be every arg, in order, correctly typed, needed to build the command
        """

        def begin_new_frame() -> None:
            if not self._top_intermediate_datablock:
                parent = self.root_intermediate_datablock
            else:
                parent = self._top_intermediate_datablock

            empty = IntermediateDatablock(
                datablock_info=DatablockInfo(
                    "EMPTY",
                    name=name_hint or self._next_empty_name(),
                    parent_info=ParentInfo(parent.datablock_info.name),
                    collection=self.root_collection,
                ),
                start_idx=None,
                count=None,
                transform_animation=None,
                show_hide_animations=[],
                bake_matrix=self._bake_matrix_stack[-1].copy(),
            )
            self._blocks.append(empty)
            parent.children.append(empty)

            self._anim_intermediate_stack.append(
                _AnimIntermediateStackEntry(IntermediateAnimation(), empty)
            )
            self._anim_count[-1] += 1
            empty.transform_animation = self._top_animation
            self._bake_matrix_stack[-1].identity()

        if directive == "VT":
            self.vt_table.vertices.append(VT(*args))
        elif directive == "IDX":
            self.vt_table.idxes.append(args[0])
        elif directive == "IDX10":
            # idx error etc
            self.vt_table.idxes.extend(args)
        elif directive == "TRIS":
            start_idx = args[0]
            count = args[1]
            if not self._anim_intermediate_stack:
                parent: IntermediateDatablock = self.root_intermediate_datablock
            else:
                parent: IntermediateDatablock = self._anim_intermediate_stack[
                    -1
                ].intermediate_datablock

            intermediate_datablock = IntermediateDatablock(
                datablock_info=DatablockInfo(
                    datablock_type="MESH",
                    name=name_hint or self._next_object_name(),
                    # How do we keep track of this
                    parent_info=ParentInfo(parent.datablock_info.name),
                    collection=self.root_collection,
                ),
                start_idx=start_idx,
                count=count,
                transform_animation=None,
                show_hide_animations=[],
                bake_matrix=self._bake_matrix_stack[-1].copy(),
            )
            intermediate_datablock.manip = copy.deepcopy(self._pending_manip)
            intermediate_datablock.attrs = copy.deepcopy(self._pending_attrs)
            self._blocks.append(intermediate_datablock)
            parent.children.append(intermediate_datablock)

        elif directive == "ANIM_begin":
            self._anim_count.append(0)
            self._bake_matrix_stack.append(self._bake_matrix_stack[-1].copy())
        elif directive == "ANIM_end":
            for i in range(self._anim_count.pop()):
                self._anim_intermediate_stack.pop()
            self._bake_matrix_stack.pop()
        elif directive == "ANIM_trans_begin":
            dataref_path = args[0]

            begin_new_frame()
            self._top_animation.xp_dataref = IntermediateDataref(
                anim_type=ANIM_TYPE_TRANSFORM,
                loop=0,
                path=dataref_path,
                show_hide_v1=0,
                show_hide_v2=0,
                location_values=[],
                rotation_values=[],
            )
        elif directive == "ANIM_trans_key":
            value = args[0]
            location = args[1]
            self._top_animation.locations.append(location)
            self._top_dataref.location_values.append(value)
        elif directive == "ANIM_trans_end":
            pass
        elif directive in {"ANIM_show", "ANIM_hide"}:
            v1, v2 = args[:2]
            dataref_path = args[2]
            begin_new_frame()
            self._top_dataref.anim_type = directive.replace("ANIM_", "")
            self._top_dataref.path = dataref_path
            self._top_dataref.show_hide_v1 = v1
            self._top_dataref.show_hide_v2 = v2
        elif directive == "ANIM_rotate_begin":
            axis = args[0]
            dataref_path = args[1]
            axis.normalize()

            self._last_axis = axis
            begin_new_frame()
            self._top_animation.xp_dataref = IntermediateDataref(
                anim_type=ANIM_TYPE_TRANSFORM,
                loop=0,
                path=dataref_path,
                show_hide_v1=0,
                show_hide_v2=0,
                location_values=[],
                rotation_values=[],
            )
        elif directive == "ANIM_rotate_key":
            value = args[0]
            degrees = args[1]
            self._top_animation.rotations[self._last_axis.freeze()].append(degrees)
            self._top_dataref.rotation_values.append(value)
        elif directive == "ANIM_rotate_end":
            self._last_axis = None
        elif directive == "ANIM_keyframe_loop":
            loop = args[0]
            self._top_dataref.loop = loop
        elif directive == "ANIM_trans":
            xyz1, xyz2 = args[0:2]
            v1, v2 = args[2:4]
            path = args[4]
            r_xyz1, r_xyz2 = (
                round_vec(xyz, PRECISION_KEYFRAME) for xyz in [xyz1, xyz2]
            )
            r_v1, r_v2 = (round(v, PRECISION_KEYFRAME) for v in [v1, v2])

            def add_as_dynamic():
                begin_new_frame()
                self._top_animation.locations.append(xyz1)
                self._top_animation.locations.append(xyz2)
                self._top_dataref.location_values.extend((v1, v2))
                self._top_dataref.path = path

            if r_xyz1 == r_xyz2 and r_v1 == r_v2:
                # print("trans, case A - static")
                self._bake_matrix_stack[-1] = self._bake_matrix_stack[
                    -1
                ] @ Matrix.Translation(xyz1)
            elif r_xyz1 == r_xyz2 and r_v1 != r_v2:
                # print("trans, case B - as dynamic")
                add_as_dynamic()
            elif r_xyz1 != r_xyz2 and r_v1 == r_v2:
                # print("trans, case C - as odd dynamic")
                add_as_dynamic()
                # TODO: make warning
                line = "bleh"
                logger.warn(
                    f"ANIM_trans"
                    f"    {c for c in xyz1}"
                    f"    {c for c in xyz2}"
                    f"    {v1} {v2} {path}`"
                    f"on line {line} has different locations but the same dataref values - it is malformed."
                    f"Fix {self._anim_intermediate_stack[-1].intermediate_datablock}"
                )
            elif r_xyz1 != r_xyz2 and r_v1 != r_v2:
                # print("trans, case D - dynamic")
                add_as_dynamic()

        elif directive == "ANIM_rotate":
            dxyz = args[0]
            r1, r2 = args[1:3]
            v1, v2 = args[3:5]
            path = args[5]

            dxyz.normalize()
            r_r1, r_r2 = (round(r, PRECISION_KEYFRAME) for r in [r1, r2])
            r_v1, r_v2 = (round(v, PRECISION_KEYFRAME) for v in [v1, v2])

            def add_as_dynamic():
                begin_new_frame()
                self._top_animation.rotations[dxyz.freeze()].append(r1)
                self._top_animation.rotations[dxyz.freeze()].append(r2)
                self._top_dataref.rotation_values.extend((v1, v2))
                self._top_dataref.path = path

            if r_r1 == r_r2 and r_v1 == r_v2:
                # print("rot, case A - static")
                self._bake_matrix_stack[-1] = (
                    self._bake_matrix_stack[-1]
                    @ Quaternion(dxyz, math.radians(r1)).to_matrix().to_4x4()
                )
                # print(
                #     "to euler in ANIM_rotate",
                #     [
                #         f"{math.degrees(c):.8f}"
                #         for c in self._bake_matrix_stack[-1].to_euler()
                #     ],
                # )
            elif r_r1 == r_r2 and r_v1 != r_v2:
                # print("rot, case B - as dynamic")
                add_as_dynamic()
            elif r_r1 != r_r2 and r_v1 == r_v2:
                # print("rot, case C - as odd dynamic")
                add_as_dynamic()
                # TODO: make warning
                line = "bleh"
                logger.warn(
                    f"ANIM_rotate"
                    f"    {Vector(c for c in dxyz)}"
                    f"    {r1} {r2}"
                    f"    {v1} {v2}"
                    f"    {path}"
                    f"\nnon line {line} has different rotation but the same dataref values - it is malformed."
                    f"Fix {self._anim_intermediate_stack[-1].intermediate_datablock}"
                )
            elif r_r1 != r_r2 and r_v1 != r_v2:
                # print("rot, case D - dynamic")
                add_as_dynamic()
        elif directive.startswith("ATTR_manip_") or directive in {
            "ATTR_axis_detented",
            "ATTR_axis_detent_range",
        }:
            c: List[str] = args[0]

            if directive == "ATTR_manip_none":
                self._pending_manip = None
            elif directive == "ATTR_manip_keyframe":
                if self._pending_manip is not None:
                    try:
                        self._pending_manip.keyframes.append(
                            (float(c[0]), float(c[1]))
                        )
                    except (IndexError, ValueError):
                        logger.warn("ATTR_manip_keyframe: could not parse values")
            elif directive == "ATTR_manip_wheel":
                if self._pending_manip is not None:
                    try:
                        self._pending_manip.wheel_delta = float(c[0])
                    except (IndexError, ValueError):
                        logger.warn("ATTR_manip_wheel: could not parse wheel delta")
            elif directive == "ATTR_axis_detented":
                if self._pending_manip is not None:
                    try:
                        self._pending_manip.has_axis_detented = True
                        self._pending_manip.detent_axis = (
                            float(c[0]),
                            float(c[1]),
                            float(c[2]),
                        )
                        self._pending_manip.detent_v1_min = float(c[3])
                        self._pending_manip.detent_v1_max = float(c[4])
                        self._pending_manip.detent_dataref = c[5] if len(c) > 5 else ""
                        self._pending_manip.manip_type = MANIP_DRAG_AXIS_DETENT
                        if len(c) > 5:
                            self._pending_manip.dataref2 = c[5]
                    except (IndexError, ValueError):
                        logger.warn("ATTR_axis_detented: could not parse values")
            elif directive == "ATTR_axis_detent_range":
                if self._pending_manip is not None:
                    try:
                        self._pending_manip.axis_detent_ranges.append(
                            (float(c[0]), float(c[1]), float(c[2]))
                        )
                        if self._pending_manip.manip_type == MANIP_DRAG_ROTATE:
                            self._pending_manip.manip_type = MANIP_DRAG_ROTATE_DETENT
                    except (IndexError, ValueError):
                        logger.warn("ATTR_axis_detent_range: could not parse values")
            else:
                manip_type = directive[len("ATTR_manip_"):]
                m = self._parse_manip_components(manip_type, c)
                if m is not None:
                    self._pending_manip = m
        elif directive in {
            "ATTR_draw_disable",
            "ATTR_draw_enable",
            "ATTR_cockpit",
            "ATTR_cockpit_lit_only",
            "ATTR_cockpit_region",
            "ATTR_cockpit_device",
            "ATTR_no_cockpit",
            "ATTR_solid_camera",
            "ATTR_no_solid_camera",
            "ATTR_shiny_rat",
        }:
            self._apply_pending_attr(directive, args[0] if args else [])
        else:
            assert False, f"{directive} is not supported yet"

    def finalize_intermediate_blocks(self) -> Set[str]:
        """The last step after parsing, converting
        data to intermediate structures, clean up and error checking.

        Returns a set with FINISHED or CANCELLED, matching the returns of bpy
        operators
        """

        def reparent_children_to_new_block(
            current_parent_block: IntermediateDatablock,
            new_parent_block: IntermediateDatablock,
        ):
            for child in current_parent_block.children:
                child.datablock_info.parent_info.parent = (
                    new_parent_block.datablock_info.name
                )
                new_parent_block.children.append(child)
            current_parent_block.children.clear()

        # Since we're using root collections mode, our INTER_ROOT empty datablock isn't made
        # and we pretend its a collection.
        blocks_rem_itr = islice(self._blocks, 1, len(self._blocks))
        while True:
            try:
                intermediate_block = next(blocks_rem_itr)
            except StopIteration:
                break
            else:
                intermediate_name = intermediate_block.datablock_info.name
                intermediate_block_type = intermediate_block.datablock_type
                intermediate_parent = intermediate_block.parent
                if intermediate_block.parent == "INTER_ROOT":
                    intermediate_block.datablock_info.parent_info = None
                intermediate_parent_info = intermediate_block.datablock_info.parent_info

            print(
                f"Deciding {intermediate_block.name}" f", parent {intermediate_parent}"
            )

            if intermediate_block_type == "EMPTY":
                # Remember, we only make empties to store animations so no try needed here

                def optimize_empty_chain(
                    in_block: IntermediateDatablock,
                    searching_itr: Iterator[IntermediateDatablock],
                ) -> Tuple[IntermediateDatablock, Iterator[IntermediateDatablock]]:
                    """
                    Cleans and optimizes IntermediateDatablocks to produce the final blocks to be created.

                    Returns next block to be created and an iterator to keep searching.

                    Current optimizations
                    Optimization                   | Requires...                                      | next_block
                    -------------------------------|--------------------------------------------------|-----------
                    merge_dref_trans_table         | is_in_block_loc_anim and is_next_block_loc_anim  |
                    add_trans_table                | both loc_anim, same rotation dref values         |
                    merge_orthogonal_rotation_axis | both rot_anim, same xp_dataref.rotation_values   | reparent children
                    take_next_block_rotations      | not in_block rot_anim, is_next_block_rot_anim    | reparent children
                    # merge_show_hide_animations   | not (is_loc_anim or is_rot_anim)                 | reparent children
                    - For the same dataref path and values, 3 orthogonal axis in a row are merged
                    - Duplicate location lists, rotations, and show/hides overwrite previous values
                    - Sequential ANIM_show/hides are merged
                    - TRIS take animations from parent empties, reducing parents

                    Arbitrary rotation axis are not supported (anywhere), locations and rotations even for the same dataref path and values are not skipped

                    Not Optimized (Yet!)
                    - Optimize out duplicate Show/Hide
                    - Sequential Axis Angle dynamic rotations with the same axis and dataref are merged into one

                    TODO Algorithms
                    - Don't reduce locations when locations are different but dataref values are same.
                    This requires user attention to fix
                    """
                    i = -1
                    while True:
                        in_block_type = in_block.datablock_type
                        in_block_animation = in_block.transform_animation
                        in_block_dataref = in_block_animation.xp_dataref
                        in_block_path = in_block_dataref.path
                        is_in_block_loc_anim = bool(in_block_animation.locations)
                        is_in_block_rot_anim = bool(in_block_animation.rotations)
                        i += 1
                        searching_itr, peek_next_block_itr = itertools.tee(
                            searching_itr
                        )

                        try:
                            next_block = next(peek_next_block_itr)
                        except StopIteration:
                            # TODO: Wait! What about self optimizations!
                            # No next block, nothing to accumulate
                            break
                        else:
                            next_name = next_block.name
                            print("next name ", next_name)
                            next_block_type = next_block.datablock_type
                            next_block_parent = next_block.parent
                            next_show_hide_animations = next_block.show_hide_animations
                            next_animation = next_block.transform_animation
                            try:
                                next_dataref = next_animation.xp_dataref
                                next_block_path = next_dataref.path
                                is_next_block_loc_anim = bool(next_animation.locations)
                                is_next_block_rot_anim = bool(next_animation.rotations)
                            except AttributeError:
                                next_dataref = None
                                next_block_path = None
                                is_next_block_loc_anim = False
                                is_next_block_rot_anim = False

                            if next_block_type == "MESH":
                                # Only collapse EMPTY→MESH when the EMPTY has an identity
                                # bake_matrix AND a single mesh child. Non-identity bake_matrix
                                # means the EMPTY carries a static pre-transform that must be
                                # preserved as a real Blender object. In that case, return
                                # in_block so it gets processed first, and the MESH is picked
                                # up on the next outer-loop iteration.
                                if (
                                    len(in_block.children) == 1
                                    and in_block.bake_matrix == Matrix.Identity(4)
                                ):
                                    next_block.transform_animation = copy.copy(
                                        in_block.transform_animation
                                    )
                                    next_block.show_hide_animations = copy.copy(
                                        in_block.show_hide_animations
                                    )
                                    next_block.datablock_info.parent_info = copy.copy(
                                        in_block.datablock_info.parent_info
                                    )
                                    return next_block, peek_next_block_itr
                                else:
                                    return in_block, searching_itr
                            elif (
                                next_block_type == "EMPTY"
                                and in_block_path == next_block_path
                            ):
                                assert "" not in {
                                    in_block_path,
                                    next_block_path,
                                }, "EMPTY cannot have no dataref"
                                # WHEN DO WE SKIP THEN NEXT BLOCK?
                                assert (
                                    next_block.is_animated
                                ), f"{next_name} is EMPTY and must have animations"

                                def merge_dref_trans_table() -> IntermediateDatablock:
                                    """
                                    Merges the translation tables of in_block and next_block,
                                    returning an altered in_block and reparenting next_block's children
                                    to in_block

                                    Covers cases like

                                    ANIM_trans VecA VecB   0 1  dref1
                                    ANIM_trans VecC VecD   3 4  dref1
                                    ANIM_trans VecE VecF   -2 2 dref1
                                    TRIS 3 3

                                    dref1, 6 frames
                                    Frame | Value | Vector
                                    ------|-------|-------
                                    1     | -2    | VecE
                                    2     | 0     | VecA
                                    3     | 1     | VecB
                                    4     | 2     | VecF
                                    5     | 3     | VecC
                                    6     | 4     | VecD

                                    This is not necissarily the end of optimizations. In this example TRIS gets this table
                                    """
                                    merged_locations = collections.defaultdict(list)
                                    for location, dref_value in itertools.chain(
                                        in_block_animation.locations,
                                        next_animation.locations,
                                    ):
                                        r_location = round_vec(
                                            location, PRECISION_KEYFRAME
                                        )
                                        # if
                                        # merged_locations[round_vec(location, PRECISION_KEYFRAME)].append(dref_value

                                if is_in_block_loc_anim and is_next_block_loc_anim:
                                    # TODO:
                                    # in_block = merge_dref_trans_table()
                                    # searching_itr = peek_next_block_itr
                                    pass

                                def add_overlaping_tables():
                                    """

                                    ANIM_trans    VecA VecB   0 1 dref1
                                    ANIM_trans    VecC VecD   0 1 dref1
                                    ANIM_trans_begin dref1
                                        ANIM_trans 0  VecE
                                        ANIM_trans 2 VecF
                                    ANIM_trans_end

                                    In this case a new table is produced
                                    ANIM_trans    VecA+VecC VecB+VecD    0 1 dref1
                                    ANIM_trans_begin dref1
                                        ANIM_trans 0 VecA+VecC+VecE
                                        ANIM_trans 1 VecB+VecD
                                        ANIM_trans 2 VecF
                                    ANIM_trans_end
                                    """
                                    pass

                                # TODO: Assumes dataref ranges are the same
                                def merge_orthogonal_rotation_axis() -> IntermediateDatablock:
                                    print("merge orthogonal axis")
                                    """
                                    Attempts to merge any mergable rotations of the next_block into
                                    the in_block. Raises ValueError if next_block has nothing to merge.

                                    Assumes that the dataref ranges are the same
                                    """
                                    merge_count = 0
                                    rotations = in_block.transform_animation.rotations
                                    for (
                                        axis,
                                        degrees,
                                    ) in next_animation.rotations.items():
                                        is_axis_aligned = is_vector_axis_aligned(axis)

                                        already_used = any(
                                            round_vec(axis, PRECISION_KEYFRAME)
                                            == round_vec(vec, PRECISION_KEYFRAME)
                                            for vec in rotations
                                        )
                                        # print("is_axis_aligned:", is_axis_aligned)
                                        # print("already_used:", already_used)

                                        if is_axis_aligned and not already_used:
                                            # print("merging: ", axis)
                                            in_block_animation.rotations[axis] = degrees
                                            merge_count += 1
                                        else:
                                            # print("not merging: ", axis)
                                            pass

                                    if merge_count:
                                        reparent_children_to_new_block(
                                            next_block,
                                            in_block,
                                        )
                                        # Clear the merged-away block's animation so
                                        # finalization doesn't create a duplicate
                                        # Blender EMPTY that re-emits these rotations.
                                        next_block.transform_animation.rotations.clear()
                                        next_block.transform_animation.xp_dataref.rotation_values.clear()
                                    else:
                                        raise ValueError

                                    return in_block

                                _something_merged = False

                                if is_in_block_rot_anim and is_next_block_rot_anim:
                                    # Merge orthogonal rotation axes into in_block
                                    try:
                                        if (
                                            in_block_animation.xp_dataref.rotation_values
                                            == next_animation.xp_dataref.rotation_values
                                        ):
                                            in_block = merge_orthogonal_rotation_axis()
                                            searching_itr = peek_next_block_itr
                                            _something_merged = True
                                        else:
                                            raise ValueError
                                    except ValueError:
                                        pass

                                def take_next_block_rotations():
                                    in_block_animation.rotations = copy.copy(
                                        next_animation.rotations
                                    )
                                    in_block_animation.xp_dataref.rotation_values = (
                                        copy.copy(
                                            next_animation.xp_dataref.rotation_values
                                        )
                                    )
                                    reparent_children_to_new_block(next_block, in_block)

                                    return in_block

                                if (
                                    not in_block_animation.is_animated_rotation
                                    and bool(next_animation.rotations)
                                    and in_block_dataref.rotation_values
                                    == next_dataref.rotation_values
                                ):
                                    in_block = take_next_block_rotations()
                                    searching_itr = peek_next_block_itr
                                    _something_merged = True

                                # Merge Show/Hides
                                def merge_show_hide_animations():
                                    """
                                    If the next EMPTY is simply a show/hide,
                                    absorb it's animations
                                    """
                                    for next_anim in (
                                        next_anim
                                        for next_anim in next_show_hide_animations
                                        if next_anim.anim_type
                                        in {ANIM_TYPE_SHOW, ANIM_TYPE_HIDE}
                                    ):
                                        in_block.show_hide_animations.append(next_anim)

                                if next_show_hide_animations:
                                    show_hide_count = len(in_block.show_hide_animations)
                                    merge_show_hide_animations()
                                    if (
                                        len(in_block.show_hide_animations)
                                        - show_hide_count
                                    ):
                                        reparent_children_to_new_block(
                                            next_block,
                                            in_block,
                                        )
                                        searching_itr = peek_next_block_itr
                                        _something_merged = True

                                if not _something_merged:
                                    # Nothing could be merged with this same-path EMPTY.
                                    # Return now to prevent an infinite loop — the outer
                                    # loop will process next_block on the next iteration.
                                    return (in_block, searching_itr)
                                # Merged something — continue inner loop to pick up any
                                # further same-path EMPTYs (e.g. 3-axis cap objects).
                            # --- end next empty with same dataref -------------
                            elif (
                                next_block_type == "EMPTY"
                                and in_block_path != next_block_path
                            ):
                                # Different dataref = search complete.
                                # outer loop will advance itr
                                return (in_block, searching_itr)

                            else:
                                assert False, f"{next_block_type} is not yet supported"

                            # What we need: Big if statement to collect optimizations to run, in what order, what should be done to the intermediate block, if you're getting rid of it who to reparent to, what shuold happen to the next block. We need a big ordered table.

                            # end if False
                    # end while
                    return (in_block, searching_itr)

                # end def optimize_empty_chain
                print(f"IN {intermediate_block.name}")
                out_block, blocks_rem_itr = optimize_empty_chain(
                    intermediate_block, blocks_rem_itr
                )
                #                print(
                #                    "location values",
                #                    out_block.transform_animation.xp_dataref.location_values,
                #                )
                #                print(
                #                    "rotation values",
                #                    out_block.transform_animation.xp_dataref.rotation_values,
                #                )

                print(
                    f"OUT {out_block.name}, parent: {out_block.parent}, type: {out_block.datablock_type}"
                )
            elif intermediate_block_type == "MESH":
                out_block = intermediate_block

            def fill_in_eulers(
                block_to_fill: IntermediateDatablock,
            ) -> Tuple[Dict[Vector, List[float]], str]:
                """
                Returns Euler rotations as a complete 3 entry dictionary, any holes filled in,
                and its accompanying rotation_mode.

                block_to_fill must be animated for rotation with
                axis-aligned vectors only.
                """

                degrees = [0.0] * len(
                    block_to_fill.transform_animation.xp_dataref.rotation_values
                )
                filled_rotations = {
                    "X": [Vector((1, 0, 0)).freeze(), degrees.copy()],
                    "Y": [Vector((0, 1, 0)).freeze(), degrees.copy()],
                    "Z": [Vector((0, 0, 1)).freeze(), degrees.copy()],
                }

                in_order = ""
                for (
                    axis,
                    degrees,
                ) in block_to_fill.transform_animation.rotations.items():
                    r_axis = tuple(
                        map(lambda c: bool(round(c, PRECISION_KEYFRAME)), axis)
                    )
                    axis_label = ["X", "Y", "Z"][r_axis.index(True)]
                    filled_rotations[axis_label] = [
                        axis.freeze(),
                        degrees,
                    ]
                    in_order += axis_label
                # If not all axis of an apparent Euler rotation
                # were given in the OBJ, we fix the rotation mode
                # based on some assumptions of what would have been good for
                # X-Plane
                if len(in_order) == 1:
                    corrected_order = "ZYX"
                elif len(in_order) == 2:
                    corrected_order = {
                        "XY": "XYZ",
                        "YZ": "XYZ",
                        "XZ": "XYZ",
                        "YX": "ZYX",
                        "ZY": "ZYX",
                        "ZX": "ZYX",
                    }[in_order]

                elif len(in_order) == 3:
                    corrected_order = in_order

                # Any good exporter would take XYZ and write
                # it as X-Plane's ZYX. The importer goes in
                # reverse
                rotation_mode = {
                    "XYZ": "ZYX",
                    "YXZ": "ZXY",
                    "XZY": "YZX",
                    "ZXY": "YXZ",
                    "YZX": "XZY",
                    "ZYX": "XYZ",
                }[corrected_order]

                # Sorting the dictionary is added only as a debugging convenience
                return (
                    {
                        axis: degrees
                        for axis_label, (axis, degrees) in sorted(
                            filled_rotations.items(),
                            key=lambda kv: rotation_mode.index(kv[0]),
                        )
                    },
                    rotation_mode,
                )

            try:
                is_all_euler = out_block.transform_animation.rotations and all(
                    is_vector_axis_aligned(axis)
                    for axis in out_block.transform_animation.rotations
                )
            except AttributeError:  # No transform_animation
                pass
            else:
                if is_all_euler:
                    (
                        out_block.transform_animation.rotations,
                        out_block.datablock_info.rotation_mode,
                    ) = fill_in_eulers(out_block)

            if out_block.datablock_type == "EMPTY":
                has_baked_rotation = (
                    out_block.bake_matrix.to_3x3().to_quaternion().angle > 1e-5
                )
                has_baked_translation = (
                    out_block.bake_matrix.to_translation().length > 1e-5
                )
                has_baked_transform = has_baked_rotation or has_baked_translation
                has_dynamic_rotation = bool(
                    out_block.transform_animation
                    and out_block.transform_animation.rotations
                )
                has_dynamic_translation = bool(
                    out_block.transform_animation
                    and out_block.transform_animation.locations
                )
                has_dynamic_animation = has_dynamic_rotation or has_dynamic_translation

                if has_baked_transform and has_dynamic_animation:
                    # The original Blender scene had two bones: a static bone
                    # carrying T @ R_static (no keyframes) and a dynamic child bone
                    # carrying only the single-axis rotation keyframes. Reconstruct
                    # that hierarchy so the exporter can round-trip correctly and
                    # drag_rotate validation (1-axis) continues to pass.

                    static_info = DatablockInfo(
                        datablock_type="EMPTY",
                        name=out_block.datablock_info.name + ".s",
                        parent_info=out_block.datablock_info.parent_info,
                        collection=out_block.datablock_info.collection,
                    )
                    ob_static = self._create_empty(static_info)
                    if ob_static.parent and out_block.bake_matrix == Matrix.Identity(4):
                        ob_static.matrix_parent_inverse = Matrix.Identity(4)
                    ob_static.matrix_local = out_block.bake_matrix.copy()
                    bpy.context.view_layer.update()
                    ob_static.rotation_mode = out_block.rotation_mode

                    dynamic_info = DatablockInfo(
                        datablock_type="EMPTY",
                        name=out_block.datablock_info.name,
                        parent_info=ParentInfo(ob_static.name),
                        collection=out_block.datablock_info.collection,
                    )
                    ob_dyn = self._create_empty(dynamic_info)
                    ob_dyn.matrix_parent_inverse = Matrix.Identity(4)
                    ob_dyn.matrix_local = Matrix.Identity(4)
                    bpy.context.view_layer.update()
                    ob_dyn.rotation_mode = out_block.rotation_mode
                    try:
                        out_block.transform_animation.apply_animation(ob_dyn)
                    except AttributeError:
                        pass
                    for animation in out_block.show_hide_animations:
                        animation.apply_animation(ob_dyn)

                    ob = None  # already fully set up; skip the shared if ob: block
                else:
                    ob = self._create_empty(out_block.datablock_info)
            elif out_block.datablock_type == "MESH":
                try:
                    ob = out_block.build_mesh(self.vt_table)
                except ValueError:
                    ob = None
                else:
                    self._assign_imported_material(ob, out_block.attrs)
                    if out_block.manip:
                        self._apply_manip_to_object(ob, out_block.manip)

            if ob:
                # When a MESH (or intermediate show/hide EMPTY) has an identity
                # bake_matrix and is parented, Blender's default behaviour sets
                # matrix_parent_inverse = parent.matrix_world.inverted() to
                # "preserve the object's current world position" (which is the
                # origin at creation time). That cancels the parent transform and
                # leaves the object at world origin. Resetting it to Identity
                # makes matrix_local=Identity mean "same world position as
                # parent", which is correct — the VT vertices are already in the
                # bone's local frame and the parent EMPTY carries the full
                # world-space transform.
                if ob.parent and out_block.bake_matrix == Matrix.Identity(4):
                    ob.matrix_parent_inverse = Matrix.Identity(4)
                ob.matrix_local = out_block.bake_matrix.copy()
                bpy.context.view_layer.update()

                ob.rotation_mode = out_block.rotation_mode

                try:
                    out_block.transform_animation.apply_animation(ob)
                except AttributeError:  # No transform animation
                    pass

                for animation in out_block.show_hide_animations:
                    animation.apply_animation(ob)

        # end while for searching remaining blocks
        # TODO: Unit test, and what about a bunch of animations that get optimized out with not TRIS blocks?
        # Put this later
        if not bpy.data.objects:
            logger.warn(".obj had no real datablocks to create")
            return {"CANCELLED"}

        bpy.context.scene.frame_set(1)

        # Write texture paths onto the exportable layer so the exporter can
        # reconstruct the TEXTURE / TEXTURE_LIT / TEXTURE_NORMAL header lines.
        layer = self.root_collection.xplane.layer
        if self.is_cockpit:
            layer.export_type = EXPORT_TYPE_COCKPIT
        if self._cockpit_panel_mode:
            layer.cockpit_panel_mode = self._cockpit_panel_mode
        if self.texture:
            layer.texture = str(self.texture)
        if self.texture_lit:
            layer.texture_lit = str(self.texture_lit)
        if self.texture_normal:
            layer.texture_normal = str(self.texture_normal)

        return {"FINISHED"}

    @property
    def _top_animation(self) -> Optional[IntermediateAnimation]:
        try:
            return self._anim_intermediate_stack[-1].animation
        except IndexError:
            return None

    @_top_animation.setter
    def _top_animation(self, value: IntermediateAnimation) -> None:
        self._anim_intermediate_stack[-1].animation = value

    @property
    def _top_intermediate_datablock(self) -> Optional[IntermediateDatablock]:
        try:
            return self._anim_intermediate_stack[-1].intermediate_datablock
        except IndexError:
            return None

    @_top_intermediate_datablock.setter
    def _top_intermediate_datablock(self, value: IntermediateDatablock) -> None:
        self._anim_intermediate_stack[-1].intermediate_datablock = value

    @property
    def _top_dataref(self) -> Optional[IntermediateDataref]:
        return self._top_animation.xp_dataref

    @_top_dataref.setter
    def _top_dataref(self, value: IntermediateDataref) -> None:
        self._top_animation.xp_dataref = value

    def _create_empty(self, info: DatablockInfo) -> bpy.types.Object:
        """
        Creates a Blender EMPTY from a DatablockInfo whose parent_info may contain
        a string parent name (our internal ParentInfo). Resolves the name to a real
        bpy.types.Object and sets ob.parent directly, bypassing the 4.3.x
        ParentInfo assertion that requires an Object at construction time.
        """
        our_parent_info = info.parent_info
        info.parent_info = None  # prevent 4.3.x set_parent call inside create_datablock_empty
        ob = test_creation_helpers.create_datablock_empty(info)
        if our_parent_info and our_parent_info.parent:
            pref = our_parent_info.parent
            parent_ob = bpy.data.objects.get(pref) if isinstance(pref, str) else pref
            if parent_ob:
                ob.parent = parent_ob
        info.parent_info = our_parent_info  # restore for future reads
        return ob

    def _next_empty_name(self) -> str:
        return (
            f"ImpEmpty."
            f"{sum(1 for block in self._blocks if block.datablock_type == 'EMPTY'):03}"
            f"_{hex(hash(self.root_collection.name))[2:6]}"
            f"_{random.randint(0,100000)}"
        )

    def _next_object_name(self) -> str:
        return (
            f"ImpMesh."
            f"{sum(1 for block in self._blocks if block.datablock_type == 'MESH'):03}"
            f"_{hex(hash(self.root_collection.name))[2:6]}"
            f"_{random.randint(0,100000)}"
        )

    def _apply_pending_attr(self, directive: str, c: List[str]) -> None:
        attrs = self._pending_attrs

        if directive == "ATTR_draw_disable":
            attrs.draw = False
        elif directive == "ATTR_draw_enable":
            attrs.draw = True
        elif directive == "ATTR_no_cockpit":
            attrs.cockpit_mode = COCKPIT_FEATURE_NONE
            attrs.cockpit_region = 0
            attrs.cockpit_device_args = ()
        elif directive == "ATTR_cockpit":
            attrs.cockpit_mode = PANEL_COCKPIT
            attrs.cockpit_region = 0
            attrs.cockpit_device_args = ()
            self._set_cockpit_panel_mode(PANEL_COCKPIT)
        elif directive == "ATTR_cockpit_lit_only":
            attrs.cockpit_mode = PANEL_COCKPIT_LIT_ONLY
            attrs.cockpit_region = 0
            attrs.cockpit_device_args = ()
            self._set_cockpit_panel_mode(PANEL_COCKPIT_LIT_ONLY)
        elif directive == "ATTR_cockpit_region":
            attrs.cockpit_mode = PANEL_COCKPIT_REGION
            try:
                attrs.cockpit_region = int(c[0])
            except (IndexError, ValueError):
                attrs.cockpit_region = 0
            attrs.cockpit_device_args = ()
            self._set_cockpit_panel_mode(PANEL_COCKPIT_REGION)
        elif directive == "ATTR_cockpit_device":
            attrs.cockpit_mode = COCKPIT_FEATURE_DEVICE
            attrs.cockpit_region = 0
            attrs.cockpit_device_args = tuple(c)
        elif directive == "ATTR_solid_camera":
            attrs.solid_camera = True
        elif directive == "ATTR_no_solid_camera":
            attrs.solid_camera = False
        elif directive == "ATTR_shiny_rat":
            try:
                attrs.shiny_rat = float(c[0])
            except (IndexError, ValueError):
                logger.warn("ATTR_shiny_rat: could not parse value")
                return
            attrs.has_explicit_shiny_rat = True

    def _set_cockpit_panel_mode(self, mode: str) -> None:
        if self._cockpit_panel_mode is None:
            self._cockpit_panel_mode = mode
        elif self._cockpit_panel_mode != mode:
            logger.warn(
                "OBJ uses mixed cockpit panel attribute modes; "
                f"keeping first mode '{self._cockpit_panel_mode}' and importing "
                f"later mode '{mode}' as close as Blender's material model allows"
            )

    def _assign_imported_material(
        self, ob: bpy.types.Object, attrs: Optional[IntermediateAttributes]
    ) -> None:
        mat = self._get_imported_material(attrs or IntermediateAttributes())
        try:
            ob.material_slots[0].material = mat
        except IndexError:
            ob.data.materials.append(mat)

    def _get_imported_material(self, attrs: IntermediateAttributes) -> bpy.types.Material:
        key = attrs.material_key()
        material = self._materials_by_attr_key.get(key)
        if material is not None:
            return material

        material = bpy.data.materials.new(
            f"ImportedMaterial.{len(self._materials_by_attr_key):03}"
        )
        material.use_nodes = True
        material.xplane.draw = attrs.draw
        material.xplane.solid_camera = attrs.solid_camera
        material["xplane_imp_suppress_default_shiny_rat"] = (
            not attrs.has_explicit_shiny_rat
        )

        if attrs.has_explicit_shiny_rat and attrs.shiny_rat is not None:
            material.specular_intensity = attrs.shiny_rat

        if attrs.cockpit_mode == COCKPIT_FEATURE_DEVICE:
            material.xplane.cockpit_feature = COCKPIT_FEATURE_DEVICE
            self._apply_cockpit_device_args(material, attrs.cockpit_device_args)
        elif attrs.cockpit_mode in {
            PANEL_COCKPIT,
            PANEL_COCKPIT_LIT_ONLY,
            PANEL_COCKPIT_REGION,
        }:
            material.xplane.cockpit_feature = COCKPIT_FEATURE_PANEL
            if attrs.cockpit_mode == PANEL_COCKPIT_REGION:
                material.xplane.cockpit_region = str(
                    max(0, min(3, attrs.cockpit_region)) + 1
                )
        else:
            material.xplane.cockpit_feature = COCKPIT_FEATURE_NONE

        self._materials_by_attr_key[key] = material
        return material

    def _apply_cockpit_device_args(
        self, material: bpy.types.Material, args: Tuple[str, ...]
    ) -> None:
        if not args:
            return
        try:
            material.xplane.device_name = args[0]
        except TypeError:
            pass
        try:
            bus_mask = int(args[1], 0)
        except (IndexError, ValueError):
            bus_mask = 0
        for i in range(6):
            try:
                setattr(material.xplane, f"device_bus_{i}", bool(bus_mask & (1 << i)))
            except TypeError:
                pass
        try:
            material.xplane.device_lighting_channel = int(args[2])
        except (IndexError, ValueError):
            pass
        try:
            material.xplane.device_auto_adjust = bool(int(args[3]))
        except (IndexError, ValueError):
            pass

    def _parse_manip_components(
        self, manip_type: str, c: List[str]
    ) -> Optional[IntermediateManipulator]:
        def f(i: int) -> float:
            return float(c[i])

        def s(i: int) -> str:
            return c[i] if i < len(c) else ""

        def tail(start: int) -> str:
            return " ".join(c[start:]) if start < len(c) else ""

        m = IntermediateManipulator(manip_type=manip_type)
        try:
            if manip_type == MANIP_DRAG_XY:
                m.cursor = s(0)
                m.dx = f(1)
                m.dy = f(2)
                m.v1_min = f(3)
                m.v1_max = f(4)
                m.v2_min = f(5)
                m.v2_max = f(6)
                m.dataref1 = s(7)
                m.dataref2 = s(8)
                m.tooltip = tail(9)
            elif manip_type == MANIP_DRAG_AXIS:
                m.cursor = s(0)
                m.dx = f(1)
                m.dy = f(2)
                m.dz = f(3)
                m.v1 = f(4)
                m.v2 = f(5)
                m.dataref1 = s(6)
                m.tooltip = tail(7)
            elif manip_type == MANIP_DRAG_AXIS_PIX:
                m.cursor = s(0)
                m.dx = f(1)
                m.step = f(2)
                m.exp = f(3)
                m.v1 = f(4)
                m.v2 = f(5)
                m.dataref1 = s(6)
                m.tooltip = tail(7)
            elif manip_type == MANIP_DRAG_ROTATE:
                m.cursor = s(0)
                m.origin = (f(1), f(2), f(3))
                m.axis = (f(4), f(5), f(6))
                m.angle1 = f(7)
                m.angle2 = f(8)
                m.lift_at_max = f(9)
                m.v1_min = f(10)
                m.v1_max = f(11)
                m.v2_min = f(12)
                m.v2_max = f(13)
                m.dataref1 = s(14)
                m.dataref2 = s(15)
                m.tooltip = tail(16)
            elif manip_type == MANIP_COMMAND:
                m.cursor = s(0)
                m.command = s(1)
                m.tooltip = tail(2)
            elif manip_type == MANIP_COMMAND_AXIS:
                m.cursor = s(0)
                m.dx = f(1)
                m.dy = f(2)
                m.dz = f(3)
                m.positive_command = s(4)
                m.negative_command = s(5)
                m.tooltip = tail(6)
            elif manip_type in {
                MANIP_COMMAND_KNOB,
                MANIP_COMMAND_SWITCH_UP_DOWN,
                MANIP_COMMAND_SWITCH_LEFT_RIGHT,
            }:
                m.cursor = s(0)
                m.positive_command = s(1)
                m.negative_command = s(2)
                m.tooltip = tail(3)
            elif manip_type in {
                MANIP_COMMAND_KNOB2,
                MANIP_COMMAND_SWITCH_UP_DOWN2,
                MANIP_COMMAND_SWITCH_LEFT_RIGHT2,
            }:
                m.cursor = s(0)
                m.command = s(1)
                m.tooltip = tail(2)
            elif manip_type == MANIP_PUSH:
                m.cursor = s(0)
                m.v_down = f(1)
                m.v_up = f(2)
                m.dataref1 = s(3)
                m.tooltip = tail(4)
            elif manip_type == MANIP_RADIO:
                m.cursor = s(0)
                m.v_down = f(1)
                m.dataref1 = s(2)
                m.tooltip = tail(3)
            elif manip_type == MANIP_TOGGLE:
                m.cursor = s(0)
                m.v_on = f(1)
                m.v_off = f(2)
                m.dataref1 = s(3)
                m.tooltip = tail(4)
            elif manip_type in {MANIP_DELTA, MANIP_WRAP}:
                m.cursor = s(0)
                m.v_down = f(1)
                m.v_hold = f(2)
                m.v1_min = f(3)
                m.v1_max = f(4)
                m.dataref1 = s(5)
                m.tooltip = tail(6)
            elif manip_type in {
                MANIP_AXIS_KNOB,
                MANIP_AXIS_SWITCH_UP_DOWN,
                MANIP_AXIS_SWITCH_LEFT_RIGHT,
            }:
                m.cursor = s(0)
                m.v1 = f(1)
                m.v2 = f(2)
                m.click_step = f(3)
                m.hold_step = f(4)
                m.dataref1 = s(5)
                m.tooltip = tail(6)
            elif manip_type == MANIP_NOOP:
                m.dataref1 = s(0)
                m.tooltip = tail(1)
            else:
                logger.warn(f"Unknown manipulator type: ATTR_manip_{manip_type}")
                return None
        except (IndexError, ValueError) as e:
            logger.warn(f"Could not parse ATTR_manip_{manip_type}: {e}")
            return None
        return m

    def _apply_manip_to_object(
        self, ob: bpy.types.Object, m: IntermediateManipulator
    ) -> None:
        manip = ob.xplane.manip
        # Only mark as an active manipulator when the OBJ is a cockpit file.
        # Non-cockpit OBJs that contain ATTR_manip_* data still get the manip
        # properties stored (as custom props for drag_rotate etc.) but
        # enabled=True without a cockpit material causes export errors.
        manip.enabled = self.is_cockpit
        manip.autodetect_datarefs = False

        try:
            manip.type = m.manip_type
        except TypeError:
            logger.warn(
                f"Could not set manipulator type '{m.manip_type}' on '{ob.name}'"
                " — verify scene xplane version supports this type"
            )

        if m.cursor:
            try:
                manip.cursor = m.cursor
            except TypeError:
                logger.warn(f"Could not set cursor '{m.cursor}' on '{ob.name}'")

        manip.tooltip = m.tooltip

        for attr in (
            "dx", "dy", "dz", "v1", "v2", "v1_min", "v1_max",
            "v2_min", "v2_max", "v_down", "v_up", "v_hold", "v_on", "v_off",
            "step", "click_step", "hold_step", "exp", "wheel_delta",
        ):
            setattr(manip, attr, getattr(m, attr))

        for attr in ("command", "positive_command", "negative_command", "dataref1", "dataref2"):
            val = getattr(m, attr)
            if val:
                setattr(manip, attr, val)

        for start, end, height in m.axis_detent_ranges:
            r = manip.axis_detent_ranges.add()
            r.start = start
            r.end = end
            r.height = height

        if m.manip_type in (MANIP_DRAG_ROTATE, MANIP_DRAG_ROTATE_DETENT):
            ob["xplane_imp_drag_rotate_origin"] = list(m.origin)
            ob["xplane_imp_drag_rotate_axis"] = list(m.axis)
            ob["xplane_imp_drag_rotate_angle1"] = m.angle1
            ob["xplane_imp_drag_rotate_angle2"] = m.angle2
            ob["xplane_imp_drag_rotate_lift_at_max"] = m.lift_at_max

        if m.has_axis_detented:
            ob["xplane_imp_detent_axis"] = list(m.detent_axis)
            ob["xplane_imp_detent_v1_min"] = m.detent_v1_min
            ob["xplane_imp_detent_v1_max"] = m.detent_v1_max
            if m.detent_dataref:
                ob["xplane_imp_detent_dataref"] = m.detent_dataref

        if m.keyframes:
            ob["xplane_imp_manip_keyframes"] = str(m.keyframes)
